INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, DUE_DATE)
VALUES ('인텔리제이 강의듣기', 'Ch01 끝내기', 'IN_PROGRESS', DATEADD('DAY', 1, CURRENT_TIMESTAMP));

INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, DUE_DATE)
VALUES ('인텔리제이 강의듣기', 'Ch02 끝내기', 'TODO', DATEADD('DAY', 2, CURRENT_TIMESTAMP));


